# Settings apply to all build contexts
[build]
  publish = "dist"

  command = "npm run build-site"

  # Without this, the necessary devDependencies may not install. We could
  # move those to full dependencies, but most of those dependencies are not
  # necessary for projects consuming this library, so that would be silly.
  NODE_ENV = "development"

