name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node LTS
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint:check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node LTS
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Install Dependencies
        run: npm ci
      - name: Run Build
        run: npm run build
